version: '3'
services: 
    python1:
        container_name: ml-api-service-1
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        command: ["pipenv", "run", "uvicorn", "fastapi_scaffolding.main:app", "--host=0.0.0.0", "--port=3000", "--workers=10"]
        # volumes: 
        #     - ./app1:/app