# This workflow will install Python dependencies, run tests, formatting and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Format with black
      run: |
        black .

    - name: Test with pytest
      run: |
        pytest

  build-push-image:
    name: Build docker image and push
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo placeholder for building/pushing image
        run: echo "I built and pushed the Docker image to your image registry"

  deploy:
    name: Deploy Python web app to <YOUR CLOUD PROVIDER>
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
     - name: Simple echo placeholder for now
       run: echo "deployed to <YOUR CLOUD PROVIDER>!"